//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKimWebService.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ContactPerson { get; set; }
        public string PhoneNumber { get; set; }
        public string AlternativePhoneNumber { get; set; }
        public Nullable<int> AddressId { get; set; }
        public int StoreTypeId { get; set; }
        public int PricingTierId { get; set; }
        public Nullable<int> ParentStoreId { get; set; }
        public bool IsActive { get; set; }
        public int AuditId { get; set; }
    }
}
